[package]
name = "bounty_board"
version = "1.0.0"
authors = []

[addresses]
bounty_board = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "m1"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
