#!/usr/bin/env bash
# Pull secrets from SSM Parameter Store into submission/frontend/.env.local
# Usage: ./scripts/pull-secrets.sh [env]
# Example: ./scripts/pull-secrets.sh dev

set -e

ENV="${1:-dev}"
PREFIX="/bountymove/${ENV}"
OUT="submission/frontend/.env.local"

echo "Pulling secrets from SSM path: ${PREFIX}"

get_param() {
  aws ssm get-parameter \
    --name "${PREFIX}/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text 2>/dev/null || echo "MISSING"
}

ANTHROPIC_API_KEY=$(get_param "ANTHROPIC_API_KEY")
AGENT_PRIVATE_KEY=$(get_param "AGENT_PRIVATE_KEY")
MODULE_ADDRESS=$(get_param "MODULE_ADDRESS")

cat > "$OUT" <<EOF
# Auto-generated by scripts/pull-secrets.sh — do not commit
NEXT_PUBLIC_MODULE_ADDRESS=${MODULE_ADDRESS}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
AGENT_PRIVATE_KEY=${AGENT_PRIVATE_KEY}
EOF

echo "Written to ${OUT}"

# Warn about placeholders
if grep -q "MISSING\|PLACEHOLDER" "$OUT"; then
  echo ""
  echo "WARNING: Some secrets are still placeholders. Set them with:"
  echo "  aws ssm put-parameter --name ${PREFIX}/ANTHROPIC_API_KEY --value 'sk-...' --type SecureString --overwrite"
  echo "  aws ssm put-parameter --name ${PREFIX}/AGENT_PRIVATE_KEY --value '0x...' --type SecureString --overwrite"
  echo "  aws ssm put-parameter --name ${PREFIX}/MODULE_ADDRESS --value '0x...' --type String --overwrite"
fi
