#!/usr/bin/env bash
# Pull secrets from SSM Parameter Store into submission/frontend/.env.local
# Usage: ./scripts/pull-secrets.sh [env]
# Example: ./scripts/pull-secrets.sh dev

set -e

ENV="${1:-dev}"
PREFIX="/bountymove/${ENV}"
OUT="submission/frontend/.env.local"

echo "Pulling secrets from SSM path: ${PREFIX}"

get_param() {
  aws ssm get-parameter \
    --name "${PREFIX}/$1" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region us-east-1 2>/dev/null || echo "MISSING"
}

ANTHROPIC_API_KEY=$(get_param "ANTHROPIC_API_KEY")
AGENT_PRIVATE_KEY=$(get_param "AGENT_PRIVATE_KEY")
MODULE_ADDRESS=$(get_param "MODULE_ADDRESS")
HUMAN_WALLET_ADDRESS=$(get_param "HUMAN_WALLET_ADDRESS")
AGENT_WALLET_ADDRESS=$(get_param "AGENT_WALLET_ADDRESS")

cat > "$OUT" <<EOF
# Auto-generated by scripts/pull-secrets.sh — do not commit
NEXT_PUBLIC_MODULE_ADDRESS=${MODULE_ADDRESS}
NEXT_PUBLIC_AGENT_WALLET_ADDRESS=${AGENT_WALLET_ADDRESS}
NEXT_PUBLIC_HUMAN_WALLET_ADDRESS=${HUMAN_WALLET_ADDRESS}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
AGENT_PRIVATE_KEY=${AGENT_PRIVATE_KEY}
EOF

echo "Written to ${OUT}"

# Warn about placeholders
if grep -q "MISSING\|PLACEHOLDER" "$OUT"; then
  echo ""
  echo "WARNING: Some secrets are still placeholders."
fi
